filter:
  excluded_paths:
      - 'tests/*'
      - 'vendor/*'

before_commands:
  - 'composer install'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  environment:
    mysql: 5.5
    postgresql: true
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false
  dependencies:
    before:
      - 'sudo mysql -e "CREATE DATABASE phuria_test"'
      - 'sudo mysql phuria_test < tests/Phuria/SQLBuilder/Test/Resources/schema.sql'
  tests:
    override:
      -
        command: 'phpunit --configuration travis.phpunit.xml'
        coverage:
          file: 'coverage.clover'
          format: 'clover'
    after:
      - 'wget https://scrutinizer-ci.com/ocular.phar'
      - 'php ocular.phar code-coverage:upload --format=php-clover --repository="g/phuria/sql-builder" coverage.clover'

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_sim: false

