filter:
  excluded_paths:
      - 'tests/*'
      - 'vendor/*'

before_commands:
  - 'composer install'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  tests:
    override:
      -
        command: 'phpunit --configuration travis.phpunit.xml'
        coverage:
          file: 'coverage.clover'
          format: 'clover'

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

